config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  root 'welcome#app'

  namespace :forest do
    post '/actions/lock' => 'users#lock'
    post '/actions/publish_article' => 'articles#publish_article'
    post '/actions/delete_picture' => 'pictures#delete_picture'
    post '/actions/republish_article' => 'articles#republish_article'
  end
  mount ForestLiana::Engine => '/forest'

  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
    passwords: 'passwords',
    sessions: 'sessions',
    omniauth_callbacks: 'omniauth'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :articles, only: %i[index show] do
        resources :comments, only: %i[index create]
        collection do
          get :top
          get :headline
        end
      end
      resources :videos, only: %i[index show] do
        resources :comments, only: %i[index create]
      end
      resources :comments, only: %i[update destroy]
      resources :users
      resources :formations, only: %i[index show] do
        collection do
          get :modules
        end
      end
    end
  end
  match '*path', to: 'welcome#app', via: :all
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def app
  end
end

app/views/welcome/app.html.erb
<%= javascript_pack_tag 'hello_react', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_pack_tag 'hello_react', 'data-turbolinks-track': 'reload' %>

app/views/welcome/home.html.erb
<h1>Welcome#home</h1>
<p>Find me in app/views/welcome/home.html.erb</p>
<nav style="text-align: right">
  <% if user_signed_in? %>
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  <% else %>
    <%= link_to('Login', new_user_session_path)  %> |
    <%= link_to('Sign Up', new_user_registration_path)  %>
  <% end %>
</nav>
<h1>Welcome#home</h1>
<p>If you're logged in, check out <%= link_to "the app", app_path %>!</p>